### ISSUE TITLE
Are our release versions supposed to be semver?

### ISSUE THREAD

**Issue by webwurst** [giantswarm/versionbundle#28]
It seems we create a release version by doing maths operations on depending version bundles. The resulting release versions will most likely have gaps between them. Since this is pretty uncommon and the reasoning behind not obvious for a customer this might be a violation of the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Since a release is basically a dependency tree of components with their fixed versions we could just calculate a hash over that automatically. After that a human assigns a version number based on [semver](https://semver.org/) when he checks and edits the release notes anyway.

**Comment by xh3b4sd** [comment]
After there have been several discussions, can we close this issue? Are there things left we have to sort? IMO all of this is discussed and decided and documented. If something is missing please point out a specific issue. Our versions are supposed to be semver. UX wise we are fine for now with gaps between versions. If this will ever be a real problem we can iterate on the matter. The point is full automation with less as possible human interaction. A human assigning a "proper version" to some magic hash is not what we want. I very much appreciate your feedback and I want to further make sure that everything is fine on this matter. So let me know when something is missing.

**Comment by webwurst** [comment]
I don't think automated releases and manually polished version numbers and release notes are contrary. But I also understand that my concerns may be distracting from our main goal right now. Thanks for listening :heart:
